services:
  postgres:
    image: bitnami/postgresql
    container_name: muauth
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=muauth
    volumes:
      - postgresql:/bitnami/postgresql
    networks:
      - backend
  redis:
    image: bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami/redis
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgresql:
    name: muauth_db
    driver: local
  redis_data:
    name: muauth_redis
    driver: local
